---
title: "Towards a standardized evaluation of imputation routines"
author: "Hanne Oberman and Gerko Vink"
date: "Department of Methodology & Statistics @ Utrecht University"
output: html_document
---

<style type="text/css">
  
body{ /* Normal  */
  font-size: 12px;
  }
td {  /* Table  */
  font-size: 12px;
}
h1.title {
  font-size: 18px;
  color: DarkBlue;
}
h1 { /* Header 1 */
  font-size: 18px;
}
h2 { /* Header 2 */
  font-size: 18px;
}
h3 { /* Header 3 */
  font-size: 18px;
}
code.r{ /* Code block */
  font-size: 12px;
}
pre { /* Code block - determines code spacing between lines */
  font-size: 14px;
}
</style>

---

This website accompanies the manuscript *Towards a standardized evaluation of imputation routines*. In this manuscript, we aim to elicit critical thinking about simulations with incomplete data and we propose the use of a set of evaluations and descriptions that would move towards a standardized evaluation of imputation routines. We summarize this set in a convenient checklist.

The [full publication archive can be found here](https://github.com/gerkovink/evaluation). Further links are:

- [The manuscript](LINK TO MANUSCRIPT)
- [The checklist](LINK TO CHECKLIST)

All the best, 

[Hanne](https://hanneoberman.github.io) and [Gerko](https://www.gerkovink.com)

---



